import Foundation
import CoreImage
import SwiftUI

/// Core data model representing the current editing session
@Observable
class ProjectState {
    /// The original full-resolution image loaded from Photos
    var originalImage: CIImage?
    
    /// The image containing baked brush edits, used as the base for new edits
    var bakedImage: CIImage?
    
    /// The downsampled image for fast UI rendering
    var displayImage: CIImage?
    
    /// The mask generated by the VisionService where the subject is white and background is black
    var subjectMask: CIImage?
    
    /// True if Vision is currently generating the mask
    var isGeneratingMask: Bool = false
    
    /// Edits applied to the whole image as a base layer
    var wholeImageEdits = EditControls()
    
    /// Edits applied to the subject
    var subjectEdits = EditControls()
    
    /// Edits applied to the background
    var backgroundEdits = EditControls()
    
    /// The custom replacement background image
    var customBackgroundImage: CIImage?
    
    /// Offset for the custom background
    var customBackgroundOffset: CGSize = .zero
    
    /// Scale for the custom background
    var customBackgroundScale: CGFloat = 1.0
    
    /// The target currently being edited
    var activeTarget: EditTarget = .wholeImage
    
    /// The interactive selection session
    var maskSession: SubjectMaskSession?
    
    /// Whether Smart Brush mode is active
    var isBrushModeActive: Bool = false
}

/// A deep-copy snapshot of the project state for undo/redo
struct ProjectStateSnapshot {
    let bakedImage: CIImage?
    let subjectMask: CIImage?
    let wholeImageEdits: EditControls
    let subjectEdits: EditControls
    let backgroundEdits: EditControls
    let customBackgroundImage: CIImage?
    let customBackgroundOffset: CGSize
    let customBackgroundScale: CGFloat
    let activeTarget: EditTarget
    let isBrushModeActive: Bool
}

