import Foundation
import CoreImage
import SwiftUI

/// Core data model representing the current editing session
@Observable
class ProjectState {
    /// The original full-resolution image loaded from Photos
    var originalImage: CIImage?
    
    /// The downsampled image for fast UI rendering
    var displayImage: CIImage?
    
    /// The mask generated by the VisionService where the subject is white and background is black
    var subjectMask: CIImage?
    
    /// True if Vision is currently generating the mask
    var isGeneratingMask: Bool = false
    
    /// Edits applied to the subject
    var subjectEdits = EditControls()
    
    /// Edits applied to the background
    var backgroundEdits = EditControls()
    
    /// The target currently being edited
    var activeTarget: EditTarget = .subject
}
